#! /bin/sh
### BEGIN INIT INFO
# Provides:          dog
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start: $named
# Should-Stop: $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dog
# Description:       Domotic OSGi Gateway service
### END INIT INFO

# Author: Dario Bonino <dario.bonino@polito.it>, Luigi De Russis <luigi.derussis@polito.it>
#

set -e

PATH=/usr/sbin:/usr/bin:/sbin:/bin
DAEMON_PATH=/home/pi/dog
NAME=start_dog
LOG_DIR=/var/log/dog
LOG_FILE_LOCATION=$LOG_DIR/dog.log
HTTP_PORT=8080
DOG_USER=pi
DOG_GROUP=users

test -x $DAEMON_PATH/$NAME || exit 0

if [ -r /etc/default/locale ]; then
  . /etc/default/locale
  export LANG
fi

. /lib/lsb/init-functions

export PATH=$PATH

if [ ! -d "$LOG_DIR" ]; then
 mkdir "$LOG_DIR"
 chown $DOG_USER:$DOG_GROUP "$LOG_DIR"
fi

case "$1" in
  start)
        log_daemon_msg "Starting Dog" "dog"
        start-stop-daemon -b --start -c $DOG_USER:$DOG_GROUP -u $DOG_USER -m --pidfile /var/run/dog.pid --chdir $DAEMON_PATH --exec $NAME -- $HTTP_PORT $LOG_FILE_LOCATION || echo -n " already running"
        log_end_msg $?
  ;;
  stop)
        log_daemon_msg "Stopping Dog" "dog"
        set +e
        start-stop-daemon --stop --quiet --signal 9 --pidfile /var/run/dog.pid  --retry 5
        rm /var/run/dog.pid
        set -e
        log_end_msg $?
  ;;
  reload)
        log_daemon_msg "Scheduling reload of Dog configuration" "dog"
        set +e
        start-stop-daemon --stop --signal USR1 --quiet --pidfile \
                /var/run/dog.pid --name dog
        set -e
        log_end_msg $?
  ;;
  status)
        status_of_proc -p /var/run/dog.pid "$DAEMON" dog && exit 0 || exit $?
  ;;
  restart|force-reload)
        $0 stop
        sleep 1
        $0 start
  ;;
  *)
        echo "Usage: /etc/init.d/dog {start|stop|restart|reload|force-reload|status}"
        exit 1
  ;;
esac

exit 0
