#!/bin/sh

exec java -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Dorg.osgi.service.http.port=$1 -DconfigFolder=configuration/config -jar org.eclipse.osgi_3.11.3.v20170209-1843.jar -console 7777 -clean > $2
